name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on:  ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: gcc  -I INC -I TEST SRC/func_add.c SRC/func_diff.c SRC/func_mul.c SRC/func_div.c test_main.c TEST/unity.c -fprofile-arcs -ftest-coverage test_main.c
    - name: run
      run: ./test.out
    - name: coverage-create
      run:  gcov test_main.c
    - name: check
      run: gcov -b test_main.c
